name: roku-analysis

on:
  pull_request:

env:
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

jobs:
  static:
    # don't run job on forks and prevent job from running twice when a PR pushes a new commit
    if: github.repository == 'jellyfin/jellyfin-roku' && github.event_name != 'pull_request' || github.repository == 'jellyfin/jellyfin-roku' && github.event.pull_request.head.repo.full_name != github.event.pull_request.base.repo.full_name
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
      - uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b # v4
        with:
          node-version: "lts/*"
          cache: "npm"
      - name: NPM install
        run: npm ci
      - name: Install roku module dependencies
        run: npm run ropm
      - name: Build dev app
        if: env.BRANCH_NAME != 'master'
        run: npm run build
      - name: Build app for production
        if: env.BRANCH_NAME == 'master'
        run: npm run build-prod
      - name: Setup Java
        uses: actions/setup-java@6a0805fcefea3d4657a47ac4c165951e33482018 # v4
        with:
          distribution: "temurin"
          java-version: "21"
      - name: Download the Static Channel Analysis CLI
        run: |
          curl -sSL "https://devtools.web.roku.com/static-channel-analysis/sca-cmd.zip" -o sca-cmd.zip
          unzip sca-cmd.zip
      - name: Run Roku Static Analysis
        run: ./sca-cmd/bin/sca-cmd ${{ github.workspace }}/build/staging --exit error
